POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoibWlzdGVyYnVtc3NzQGdtYWlsLmNvbSIsImlhdCI6MTczMzk4NDc2MiwiZXhwIjoxNzMzOTg4MzYyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.H6s8vVqQU8dVNnjP-unyBu_31oVdtm-X4Z5VqX1ax28

{
  "title": "What's new with NestJS",
  "postType": "post",
  "slug": "new-with-nestjs-4new1234asdasdassmmd",
  "status": "draft",
  "content": "test content",
  "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\": \"Person\"\r\n }",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2024-12-16T07:46:32+0000",
  //"tags": ["nestjs", "typescript"],
  "metaOptions" : {
      "metaValue": "{\"sidebarEnabled\": true, \"footerActive\":true}"
    },
  "tags": [1, 3]
}