POST http://localhost:3000/uploads/file
Content-Type: multipart/form-data; boundary=WebKitFormBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaWx5YUBnbWFpbC5jb20iLCJpYXQiOjE3MzQzODA5NTgsImV4cCI6MTczNDM4NDU1OCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.6GhdGsJB7HPaHWuBK837qUbCOk0NuX6ybDwBZDBnhOA

file
--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="test-image.jpeg"
Content-Type: image/jpg

< ./test-image.jpeg
--WebKitFormBoundary--