version: '3.9'

networks:
  nest-masterclass-network:
    name: nest-masterclass-network

volumes:
  nest-masterclass-db-data:
    name: nest-masterclass-db-data

services:
    postgres:
        container_name: nest-masterclass-postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: someuser
            POSTGRES_PASSWORD: somepassword
            POSTGRES_DB: NestMasterclass
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - nest-masterclass-db-data:/var/lib/postgresql/data/pgdata
        ports:
            - "15432:5432"
        restart: unless-stopped