POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImlhdCI6MTczMzg3NDkxMywiZXhwIjoxNzMzOTYxMzEzLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.kld5p3t5Xu49e5fZF0R_R5Fj-cjuMTIh_Ayl8QqFAdE"

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImlhdCI6MTczMzg3NDkxMywiZXhwIjoxNzMzOTYxMzEzLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.kld5p3t5Xu49e5fZF0R_R5Fj-cjuMTIh_Ayl8QqFAdE"
}