POST http://localhost:3000/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaWx5YUBnbWFpbC5jb20iLCJpYXQiOjE3MzM5NDQyNzUsImV4cCI6MTczMzk0Nzg3NSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.jkCoz3PS0BT1ZgCclBQvlfTBSSzJkZ5NIuR9c1BgypQ

{
  "name": "dotnet",
  "slug": "dotnet",
  "description": "All posts dotnet"
}